spring.application.name=globoplast-java
server.address=127.0.0.1
server.port=8080
server.forward-headers-strategy=native
server.max-http-request-header-size=32KB
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
vaadin.launch-browser=false
logging.level.org.atmosphere=WARN
logging.level.com.vaadin.flow.server.communication.PushAtmosphereHandler=WARN
